### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/Bundles#3]
```
[17:16:50 INFO]: [Bundles] Enabling Bundles v1.1
[17:16:50 ERROR]: Error occurred while enabling Bundles v1.1 (Is it up to date?)
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
        at com.mineinabyss.idofront.plugin.RegistrationKt.registerEvents(Registration.kt) ~[Bundles-1.1-all.jar:?]
        at com.mineinabyss.bundles.BundlesPlugin.onEnable(BundlesPlugin.kt:11) ~[Bundles-1.1-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-344]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-344]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-344]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:262) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:393) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-344]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-344]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-344]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Paper-344]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:529) ~[patched_1.17.1.jar:git-Paper-344]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:491) ~[patched_1.17.1.jar:git-Paper-344]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Paper-344]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[patched_1.17.1.jar:git-Paper-344]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-344]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[patched_1.17.1.jar:git-Paper-344]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-344]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 20 more
[17:16:50 INFO]: [Bundles] Disabling Bundles v1.1
```

**Comment by Boy0000** [comment]
fixed
